name: Publish Client Libraries

on:
  push:
    branches:
      - master

jobs:
  build_test_deploy:
    continue-on-error: true
    strategy:
      matrix:
        include:
          # Windows
          - platform: windows-latest
            target: x86_64-pc-windows-msvc
            tests: true
            rustflags: -C target-feature=+crt-static
          - platform: windows-latest
            target: i686-pc-windows-msvc
            rustflags: -C target-feature=+crt-static
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - run: ./install-deps.sh
      working-directory: tunshell-client/build
      shell: bash
      env:
        TEMPDIR: /tmp

    - run: ./compile.sh ${{ matrix.target }} $PWD/artifacts/client
      working-directory: tunshell-client/build
      shell: bash
      env:
        RUN_TESTS: ${{ matrix.tests }}
        RUST_TEST_THREADS: 1
        CI: true
        RUST_LOG: debug
        RUSTFLAGS: ${{ matrix.rustflags }}
        CC: ${{ matrix.cc }}

    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ARTIFACT_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.ARTIFACT_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Deploy artifact to https://artifacts.tunshell.com
    - name: Deploy to S3
      run: >
        aws s3 cp $PWD/artifacts/client s3://tunshell-artifacts/client-${{ matrix.client_binary_name || matrix.target }}
        --acl=public-read 
        --cache-control max-age=31536000
        --metadata "sha256=$(openssl sha256 -r $PWD/artifacts/client | awk '{print $1}')"
        --metadata-directive REPLACE
      working-directory: tunshell-client/build
      shell: bash

    - name: Invalidate CloudFront
      run: aws cloudfront create-invalidation --distribution-id=E3DF4SGU15BNWT --paths '/*'
    
    - name: Setup VSCode Server session
      uses: NyaMisty/vscode-server-action@main
      if: failure()
      with:
        #machineName: myMachine # optional, default: GitHub workflow run ID
        timeout: '3600000' # 1 hour
